modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/AppliedEnergistics/Immersive-Energistics/issues"
license = "LGPLv3"

[[mods]]
modId = "immeng"
version = "${version}"
displayName = "Immersive Energistics"
description = "Adds ME-capable wires to Immersive Engineering."
displayURL = "https://github.com/AppliedEnergistics/Immersive-Energistics"
logoFile = "logo.png"
authors = "Technici4n"

[[dependencies.immersivewiring]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersivewiring]]
modId = "ae2"
type = "required"
versionRange = "${ae2_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.immersivewiring]]
modId = "immersiveengineering"
type = "required"
versionRange = "${ie_version_range}"
ordering = "AFTER"
side = "BOTH"
