name: Build
on:
  - pull_request
  - push

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Generate assets
        run: ./gradlew runData
      - name: Check that datagen ran
        run: test -d ./src/generated/resources/.cache
      - name: Make sure that datagenned files in the repo are up-to-date
        run: |
          # Print status for easier debugging
          git status
          if [ -n "$(git status --porcelain)" ]; then exit 1; fi
      - name: Build
        run: ./gradlew build --max-workers 1
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: immersive-energistics
          path: build/libs/
